# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Emily LaFollette
description: My website
baseurl: ""
url: "https://emilloohoo.github.io"
og_image: /assets/img/profile-pic.png

header:
  pages:
    - name: Home
      slug: /
    - name: Resume
    - name: Projects

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: brent.emilyy@gmail.com
  follow:
    - type: linkedin
      name: LinkedIn
      link: http://linkedin.com/in/brentemi
    - type: github
      name: GitHub
      link: https://github.com/emilloohoo

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

remote_theme: eliottvincent/bay

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
