domain: "emilloohoo.github.io"
url: "https://emilloohoo.github.io"
base_url: ""

header:
  pages:
  - name: Home
    layout: home
    slug: /
  - name: Projects  # <-- blog.md
  - name: Resume 
    layout: resume

footer:
  show_powered_by: false
  contact:
    - type: email
      name: Email
      value: brent.emilyy@gmail.com
      link: mailto:brent.emilyy@gmail.com
  follow:
    - name: LinkedIn
      link: https://linkedin.com/in/brentemi
    - name: GitHub
      link: https://github.com/emilloohoo

# Build settings
theme: bay_jekyll_theme
plugins:
  - jekyll-feed

